import Empleado
import Visitante
nombre=input("Cual es su nombre?: ")
apellido=input("Cual es su apellido?: ")
edad=int(input("Cual es su edad?: "))
puesto=input("Que empleo tiene?: ")
salario=int(input("Cuanto es su salario al mes?: "))
E=Empleado.Empleado(nombre,apellido,edad,puesto,salario)
print(E.imprimir())
E.trabajar()
E.pago()
E.setNombre("Juan")
E.getNombre()
E.setSalario(2500)
E.getSalario()
print(E.imprimir())
Nombre=input("Cual es su nombre?: ")
Apellido=input("Cual es su apellido?: ")
Edad=int(input("Cual es su edad?: "))
Fecha=(input("En que fecha nos visita?: "))
V=Visitante.Visitante(Nombre,Apellido,Edad,Fecha)
print(V.imprimir())
V.visita()
V.rompe()
V.pago()
V.setNombre("Maria")
V.getNombre()
V.setFecha("09/11/2020")
V.getFecha()
print(V.imprimir())
