version: "3.1"

services:
  servidorBD:
    image: webdevops/php-apache:7.4
    container_name: testBD
    environment:
      PHP_DISPLAY_ERRORS: 0
    ports:
    - 82:80
    volumes:
    - ./appcode:/app